### ISSUE TITLE
Forecast heure par heure

### ISSUE THREAD

**Issue by prigal** [Axellum/lovelace-icones-weather-card#6]
Hello,

J'ai posé une question ici https://github.com/hacf-fr/lovelace-meteofrance-weather-card/issues/60 et juste après je suis tombé sur ce fork et j'ai vu ce screen en readme : 

![image](https://github.com/Axellum/lovelace-meteofrance-weather-card/raw/Meteo-France/h_prev.png?raw=true)

Quel paramétrage faire pour obtenir le forecast heure par heure ?

**Comment by prigal** [comment]
My bad, j'ai eu une réponse sur l'autre thread, c'était une config au niveau de l'intégration.

**Comment by Axellum** [comment]
Pour celle ci je l'est fais avec un autre weather (celui de base), qui propose d activer en option weather.maison_hourly. Du coup tu peut monter 2 cartes sur le même endroit (même si le village d'à coté fais l'affaire aussi ^^): 
<img width="383" alt="Capture d’écran 2020-11-13 075617" src="https://user-images.githubusercontent.com/60935256/99041066-86126880-258a-11eb-982b-320da70da0af.png">
